/*
  This file is automatically generated. Any changes will be overwritten.
  Modify tracks.component.ts instead.
*/
import { Injector, OnInit, OnDestroy } from '@angular/core';
import { NavigationEnd, Router, ActivatedRoute } from '@angular/router';
import { Location } from '@angular/common';
import { Subscription } from 'rxjs';

import { SpotifyService } from '../spotify.service';

/*
  Component properties set from design-time.
*/
const { components } = require('../../../../meta/pages/tracks.json');

export class TracksGenerated implements OnInit, OnDestroy {
  components = components;
  // Array of messages displayed by the notification component.
  messages = [];

  router: Router;

  route: ActivatedRoute;

  _location: Location;

  subscription: Subscription;


  spotify: SpotifyService;

  tracks: any;

  parameters: any;

  ngOnInit() {
    this.subscription = this.router.events.subscribe(event => {
      if (event instanceof NavigationEnd && this instanceof <any>this.route.component) {
        this.parameters = this.route.snapshot.params;

        this.load();
      }
    });
  }

  ngOnDestroy() {
    this.subscription.unsubscribe();
  }


  load() {
    this.spotify.getAlbumTracks(`${this.parameters.id}`)
    .then(result => {
      this.tracks = result.items;
    }, result => {

    });
  }

  constructor(injector: Injector) {
    this.router = injector.get(Router);

    this._location = injector.get(Location);

    this.route = injector.get(ActivatedRoute);

    this.spotify = injector.get(SpotifyService);
  }
}
