/*
  This file is automatically generated. Any changes will be overwritten.
  Modify main-layout.component.ts instead.
*/
import { LOCALE_ID, ChangeDetectorRef, ViewChild, AfterViewInit, Injector, OnInit, OnDestroy } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { Location } from '@angular/common';
import { HttpClient, HttpParams, HttpHeaders } from '@angular/common/http';
import { Subscription } from 'rxjs/Subscription';

import { DialogService, DIALOG_PARAMETERS, DialogRef } from '@radzen/angular/dist/dialog';
import { NotificationService } from '@radzen/angular/dist/notification';
import { HeaderComponent } from '@radzen/angular/dist/header';
import { SidebarToggleComponent } from '@radzen/angular/dist/sidebar-toggle';
import { ImageComponent } from '@radzen/angular/dist/image';
import { LabelComponent } from '@radzen/angular/dist/label';
import { ProfileMenuComponent } from '@radzen/angular/dist/profilemenu';
import { BodyComponent } from '@radzen/angular/dist/body';
import { ContentContainerComponent } from '@radzen/angular/dist/content-container';
import { SidebarComponent } from '@radzen/angular/dist/sidebar';
import { PanelMenuComponent } from '@radzen/angular/dist/panelmenu';
import { FooterComponent } from '@radzen/angular/dist/footer';

import { SecurityService } from '../security.service';

export class MainLayoutGenerated implements AfterViewInit, OnInit, OnDestroy {
  // Components
  @ViewChild('header0') header0: HeaderComponent;
  @ViewChild('sidebar-toggle0') sidebarToggle0: SidebarToggleComponent;
  @ViewChild('image1') image1: ImageComponent;
  @ViewChild('label0') label0: LabelComponent;
  @ViewChild('profilemenu0') profilemenu0: ProfileMenuComponent;
  @ViewChild('body0') body0: BodyComponent;
  @ViewChild('main') main: ContentContainerComponent;
  @ViewChild('sidebar0') sidebar0: SidebarComponent;
  @ViewChild('panelmenu0') panelmenu0: PanelMenuComponent;
  @ViewChild('footer0') footer0: FooterComponent;
  @ViewChild('footerText') footerText: LabelComponent;

  router: Router;

  cd: ChangeDetectorRef;

  route: ActivatedRoute;

  notificationService: NotificationService;

  dialogService: DialogService;

  dialogRef: DialogRef;

  httpClient: HttpClient;

  locale: string;

  _location: Location;

  _subscription: Subscription;

  security: SecurityService;
  userData: any;
  parameters: any;

  constructor(private injector: Injector) {
  }

  ngOnInit() {
    this.notificationService = this.injector.get(NotificationService);

    this.dialogService = this.injector.get(DialogService);

    this.dialogRef = this.injector.get(DialogRef, null);

    this.locale = this.injector.get(LOCALE_ID);

    this.router = this.injector.get(Router);

    this.cd = this.injector.get(ChangeDetectorRef);

    this._location = this.injector.get(Location);

    this.route = this.injector.get(ActivatedRoute);

    this.httpClient = this.injector.get(HttpClient);

    this.security = this.injector.get(SecurityService);
  }

  ngAfterViewInit() {
    this._subscription = this.route.params.subscribe(parameters => {
      if (this.dialogRef) {
        this.parameters = this.injector.get(DIALOG_PARAMETERS);
      } else {
        this.parameters = parameters;
      }
      this.load();
      this.cd.detectChanges();
    });
  }

  ngOnDestroy() {
    this._subscription.unsubscribe();
  }


  load() {
    this.httpClient.request('get', 'http://localhost:5000/api/ServerMethods/UserPersonalData', {
      headers: new HttpHeaders({
        'Authorization': `Bearer ${this.security.token}`
      })
    })
    .subscribe((result: any) => {
      this.userData = result;
    }, (result: any) => {

    });
  }

  profilemenu0Click(event: any) {
    if (event.text == 'Logout') {
      this.security.logout()
    }
  }
}
