/*
  This file is automatically generated. Any changes will be overwritten.
  Modify app.module.ts instead.
*/
import { BrowserModule } from '@angular/platform-browser';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { FormsModule } from '@angular/forms';
import { HttpClientModule, HTTP_INTERCEPTORS } from '@angular/common/http';

import { RadzenModule } from '@radzen/angular';

import { AppRoutes } from './app.routes';
import { AppComponent, PageTitleComponent, NavigationMenuComponent } from './app.component';
export { AppComponent } from './app.component';
import { OrdersComponent } from './orders/orders.component';
import { AddOrderComponent } from './add-order/add-order.component';
import { EditOrderComponent } from './edit-order/edit-order.component';
import { OrderDetailsComponent } from './order-details/order-details.component';
import { AddOrderDetailComponent } from './add-order-detail/add-order-detail.component';
import { EditOrderDetailComponent } from './edit-order-detail/edit-order-detail.component';
import { ProductsComponent } from './products/products.component';
import { AddProductComponent } from './add-product/add-product.component';
import { EditProductComponent } from './edit-product/edit-product.component';

import { SampleService } from './sample.service';

export const PageDeclarations = [
  OrdersComponent,
  AddOrderComponent,
  EditOrderComponent,
  OrderDetailsComponent,
  AddOrderDetailComponent,
  EditOrderDetailComponent,
  ProductsComponent,
  AddProductComponent,
  EditProductComponent,
  PageTitleComponent
];

export const AppDeclarations = [
  ...PageDeclarations,
  AppComponent,
  NavigationMenuComponent
];

export const AppProviders = [
  SampleService,
];

export const AppImports = [
  BrowserModule,
  BrowserAnimationsModule,
  FormsModule,
  HttpClientModule,
  RadzenModule,
  AppRoutes
];
