/*
  This file is automatically generated. Any changes will be overwritten.
  Modify orders-by-product-id.component.ts instead.
*/
import { LOCALE_ID, ChangeDetectorRef, ViewChild, AfterViewInit, Injector, OnInit, OnDestroy } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { Location } from '@angular/common';
import { HttpClient, HttpParams, HttpHeaders } from '@angular/common/http';
import { Subscription } from 'rxjs';

import { DialogService, DIALOG_PARAMETERS, DialogRef } from '@radzen/angular/dist/dialog';
import { NotificationService } from '@radzen/angular/dist/notification';
import { ContentComponent } from '@radzen/angular/dist/content';
import { HeadingComponent } from '@radzen/angular/dist/heading';
import { GridComponent } from '@radzen/angular/dist/grid';
import { LinkComponent } from '@radzen/angular/dist/link';

import { ConfigService } from '../config.service';
import { AddOrderDetailComponent } from '../add-order-detail/add-order-detail.component';

import { NorthwindService } from '../northwind.service';
import { SecurityService } from '../security.service';

export class OrdersByProductIdGenerated implements AfterViewInit, OnInit, OnDestroy {
  // Components
  @ViewChild('content1') content1: ContentComponent;
  @ViewChild('pageTitle') pageTitle: HeadingComponent;
  @ViewChild('grid0') grid0: GridComponent;

  router: Router;

  cd: ChangeDetectorRef;

  route: ActivatedRoute;

  notificationService: NotificationService;

  configService: ConfigService;

  dialogService: DialogService;

  dialogRef: DialogRef;

  httpClient: HttpClient;

  locale: string;

  _location: Location;

  _subscription: Subscription;

  northwind: NorthwindService;

  security: SecurityService;
  parameters: any;
  getOrderDetailsResult: any;
  getOrderDetailsCount: any;
  product: any;

  constructor(private injector: Injector) {
  }

  ngOnInit() {
    this.notificationService = this.injector.get(NotificationService);

    this.configService = this.injector.get(ConfigService);

    this.dialogService = this.injector.get(DialogService);

    this.dialogRef = this.injector.get(DialogRef, null);

    this.locale = this.injector.get(LOCALE_ID);

    this.router = this.injector.get(Router);

    this.cd = this.injector.get(ChangeDetectorRef);

    this._location = this.injector.get(Location);

    this.route = this.injector.get(ActivatedRoute);

    this.httpClient = this.injector.get(HttpClient);

    this.northwind = this.injector.get(NorthwindService);
    this.security = this.injector.get(SecurityService);
  }

  ngAfterViewInit() {
    this._subscription = this.route.params.subscribe(parameters => {
      if (this.dialogRef) {
        this.parameters = this.injector.get(DIALOG_PARAMETERS);
      } else {
        this.parameters = parameters;
      }
      this.load();
      this.cd.detectChanges();
    });
  }

  ngOnDestroy() {
    this._subscription.unsubscribe();
  }


  load() {
    this.grid0.load();
  }

  grid0Add(event: any) {
    this.dialogService.open(AddOrderDetailComponent, { parameters: {}, title: `Add Order Detail` });
  }

  grid0LoadData(event: any) {
    this.northwind.getOrderDetails(`${event.filter ? event.filter + ' and ' : ''}ProductID eq ${this.parameters.ProductID}`, event.top, event.skip, `${event.orderby}`, event.top != null && event.skip != null, `Order($expand=Customer),Product`, null, null)
    .subscribe((result: any) => {
      this.getOrderDetailsResult = result.value;

      this.getOrderDetailsCount = event.top != null && event.skip != null ? result['@odata.count'] : result.value.length;

      this.product = result.value[0].Product;
    }, (result: any) => {

    });
  }
}
