/*
  This file is automatically generated. Any changes will be overwritten.
  Modify customers.component.ts instead.
*/
import { ChangeDetectorRef, ViewChild, AfterViewInit, Injector, OnInit, OnDestroy } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { Location } from '@angular/common';
import { Subscription } from 'rxjs/Subscription';

import { DialogService, DIALOG_PARAMETERS, DialogRef } from '@radzen/angular/dist/dialog';
import { NotificationService } from '@radzen/angular/dist/notification';
import { ContentComponent } from '@radzen/angular/dist/content';
import { HeadingComponent } from '@radzen/angular/dist/heading';
import { GridComponent } from '@radzen/angular/dist/grid';
import { AddOrderComponent } from '../add-order/add-order.component';
import { AddCustomerComponent } from '../add-customer/add-customer.component';
import { EditCustomerComponent } from '../edit-customer/edit-customer.component';
import { EditOrderComponent } from '../edit-order/edit-order.component';

import { NorthwindService } from '../northwind.service';

export class CustomersGenerated implements AfterViewInit, OnInit, OnDestroy {
  // Components
  @ViewChild('content1') content1: ContentComponent;
  @ViewChild('pageTitle') pageTitle: HeadingComponent;
  @ViewChild('grid0') grid0: GridComponent;
  @ViewChild('heading1') heading1: HeadingComponent;
  @ViewChild('grid1') grid1: GridComponent;

  router: Router;

  cd: ChangeDetectorRef;

  route: ActivatedRoute;

  notificationService: NotificationService;

  dialogService: DialogService;

  dialogRef: DialogRef;

  _location: Location;

  _subscription: Subscription;

  northwind: NorthwindService;

  getCustomersResult: any;

  getCustomersCount: any;

  parameters: any;

  master: any;

  Orders: any;

  constructor(private injector: Injector) {
  }

  ngOnInit() {
    this.notificationService = this.injector.get(NotificationService);

    this.dialogService = this.injector.get(DialogService);

    this.dialogRef = this.injector.get(DialogRef, null);

    this.router = this.injector.get(Router);

    this.cd = this.injector.get(ChangeDetectorRef);

    this._location = this.injector.get(Location);

    this.route = this.injector.get(ActivatedRoute);

    this.northwind = this.injector.get(NorthwindService);
  }

  ngAfterViewInit() {
    this._subscription = this.route.params.subscribe(parameters => {
      if (this.dialogRef) {
        this.parameters = this.injector.get(DIALOG_PARAMETERS);
      } else {
        this.parameters = parameters;
      }
      this.load();
      this.cd.detectChanges();
    });
  }

  ngOnDestroy() {
    this._subscription.unsubscribe();
  }


  load() {
    this.northwind.getCustomers(null, this.grid0.allowPaging ? this.grid0.pageSize : null, this.grid0.allowPaging ? 0 : null, null, this.grid0.allowPaging, null, null, null)
    .subscribe((result: any) => {
      this.getCustomersResult = result.value;

      this.getCustomersCount = this.grid0.allowPaging ? result['@odata.count'] : result.value.length;

      if (result.value.length) {
        this.grid0.onSelect(result.value[0])
      }
    }, (result: any) => {

    });
  }

  grid0LoadData(event: any) {
    this.northwind.getCustomers(`${event.filter}`, event.top, event.skip, `${event.orderby}`, event.top != null && event.skip != null, ``, null, null)
    .subscribe((result: any) => {
      this.getCustomersResult = result.value;

      this.getCustomersCount = event.top != null && event.skip != null ? result['@odata.count'] : result.value.length;
    }, (result: any) => {

    });
  }

  grid0Delete(event: any) {
    this.northwind.deleteCustomer(`${event.CustomerID}`)
    .subscribe((result: any) => {
      this.notificationService.notify({ severity: "success", summary: `Success`, detail: `Customer deleted!` });
    }, (result: any) => {
      this.notificationService.notify({ severity: "error", summary: `Error`, detail: `Unable to delete Customer` });
    });
  }

  grid0Add(event: any) {
    this.dialogService.open(AddCustomerComponent, { parameters: {}, title: 'Add Customer' });
  }

  grid0RowDoubleClick(event: any) {
    this.dialogService.open(EditCustomerComponent, { parameters: {CustomerID: event.CustomerID}, title: 'Edit Customer' });
  }

  grid0RowSelect(event: any) {
    this.master = event;

    this.northwind.getOrders(`CustomerID eq '${event.CustomerID}'`, null, null, null, null, `Customer,Employee,Shipper`, null, null)
    .subscribe((result: any) => {
      this.Orders = result.value;
    }, (result: any) => {

    });
  }

  grid1Add(event: any) {
    this.dialogService.open(AddOrderComponent, { parameters: {CustomerID: this.master.CustomerID}, title: 'Add Order' });
  }

  grid1Delete(event: any) {
    this.northwind.deleteOrder(event.OrderID)
    .subscribe((result: any) => {
      this.notificationService.notify({ severity: "success", summary: `Success`, detail: `Order deleted!` });
    }, (result: any) => {
      this.notificationService.notify({ severity: "error", summary: `Error`, detail: `Unable to delete Order` });
    });
  }

  grid1RowSelect(event: any) {
    this.dialogService.open(EditOrderComponent, { parameters: {OrderID: event.OrderID}, title: 'Edit Order' });
  }
}
