/*
  This file is automatically generated. Any changes will be overwritten.
  Modify edit-order.component.ts instead.
*/
import { LOCALE_ID, ChangeDetectorRef, ViewChild, AfterViewInit, Injector, OnInit, OnDestroy } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { Location } from '@angular/common';
import { HttpClient, HttpParams, HttpHeaders } from '@angular/common/http';
import { Subscription } from 'rxjs/Subscription';

import { DialogService, DIALOG_PARAMETERS, DialogRef } from '@radzen/angular/dist/dialog';
import { NotificationService } from '@radzen/angular/dist/notification';
import { ContentComponent } from '@radzen/angular/dist/content';
import { LabelComponent } from '@radzen/angular/dist/label';
import { ButtonComponent } from '@radzen/angular/dist/button';
import { TemplateFormComponent } from '@radzen/angular/dist/template-form';
import { TextBoxComponent } from '@radzen/angular/dist/textbox';
import { RequiredValidatorComponent } from '@radzen/angular/dist/required-validator';
import { DatePickerComponent } from '@radzen/angular/dist/datepicker';
import { DropDownComponent } from '@radzen/angular/dist/dropdown';

import { ConfigService } from '../config.service';

import { SampleService } from '../sample.service';

export class EditOrderGenerated implements AfterViewInit, OnInit, OnDestroy {
  // Components
  @ViewChild('content1') content1: ContentComponent;
  @ViewChild('closeLabel') closeLabel: LabelComponent;
  @ViewChild('closeButton') closeButton: ButtonComponent;
  @ViewChild('form0') form0: TemplateFormComponent;
  @ViewChild('label2') label2: LabelComponent;
  @ViewChild('UserName') userName: TextBoxComponent;
  @ViewChild('UserNameRequiredValidator') userNameRequiredValidator: RequiredValidatorComponent;
  @ViewChild('label3') label3: LabelComponent;
  @ViewChild('OrderDate') orderDate: DatePickerComponent;
  @ViewChild('OrderDateRequiredValidator') orderDateRequiredValidator: RequiredValidatorComponent;
  @ViewChild('label4') label4: LabelComponent;
  @ViewChild('OrderDetails') orderDetails: DropDownComponent;
  @ViewChild('button2') button2: ButtonComponent;
  @ViewChild('button3') button3: ButtonComponent;

  router: Router;

  cd: ChangeDetectorRef;

  route: ActivatedRoute;

  notificationService: NotificationService;

  configService: ConfigService;

  dialogService: DialogService;

  dialogRef: DialogRef;

  httpClient: HttpClient;

  locale: string;

  _location: Location;

  _subscription: Subscription;

  sample: SampleService;
  canEdit: any;
  order: any;
  allProducts: any;
  currentProducts: any;
  parameters: any;

  constructor(private injector: Injector) {
  }

  ngOnInit() {
    this.notificationService = this.injector.get(NotificationService);

    this.configService = this.injector.get(ConfigService);

    this.dialogService = this.injector.get(DialogService);

    this.dialogRef = this.injector.get(DialogRef, null);

    this.locale = this.injector.get(LOCALE_ID);

    this.router = this.injector.get(Router);

    this.cd = this.injector.get(ChangeDetectorRef);

    this._location = this.injector.get(Location);

    this.route = this.injector.get(ActivatedRoute);

    this.httpClient = this.injector.get(HttpClient);

    this.sample = this.injector.get(SampleService);
  }

  ngAfterViewInit() {
    this._subscription = this.route.params.subscribe(parameters => {
      if (this.dialogRef) {
        this.parameters = this.injector.get(DIALOG_PARAMETERS);
      } else {
        this.parameters = parameters;
      }
      this.load();
      this.cd.detectChanges();
    });
  }

  ngOnDestroy() {
    this._subscription.unsubscribe();
  }


  load() {
    this.canEdit = true;

    this.sample.getOrderById(null, this.parameters.Id)
    .subscribe((result: any) => {
      this.order = result;
    }, (result: any) => {
      this.canEdit = !(result.status == 400);
    });

    this.sample.getProducts(null, null, null, `ProductName asc`, null, null, null, null)
    .subscribe((result: any) => {
      this.allProducts = result.value;
    }, (result: any) => {

    });

    this.sample.getOrderDetails(`OrderId eq ${this.parameters.Id}`, null, null, null, null, `Product`, null, null)
    .subscribe((result: any) => {
      this.currentProducts = result.value.map(orderDetail => orderDetail.Product);
    }, (result: any) => {

    });
  }

  closeButtonClick(event: any) {
    if (this.dialogRef) {
      this.dialogRef.close();
    } else {
      this._location.back();
    }
  }

  form0Submit(event: any) {
    this.sample.updateOrder(null, this.parameters.Id, event)
    .subscribe((result: any) => {
      if (this.dialogRef) {
        this.dialogRef.close();
      } else {
        this._location.back();
      }
    }, (result: any) => {
      this.canEdit = !(result.status == 400);

      this.notificationService.notify({ severity: "error", summary: `Error`, detail: `Unable to update Order` });
    });

    this.httpClient.request('post', `${this.configService.get('serverMethodsUrl')}api/ServerMethods/UpdateProducts`, {
      withCredentials: true,
      body: { orderId: this.parameters.Id, products: this.currentProducts }
    })
    .subscribe((result: any) => {

    }, (result: any) => {

    });
  }

  button3Click(event: any) {
    if (this.parameters.isAdd) {
          this.sample.deleteOrder(this.parameters.Id)
      .subscribe((result: any) => {
    
      }, (result: any) => {
    
      });
    }

    if (this.dialogRef) {
      this.dialogRef.close();
    } else {
      this._location.back();
    }
  }
}
